//------------------------------------------------------------------------------
// <autogenerated>
//     This Oxygene source code was generated by a tool.
//     Runtime Version: 4.0.30319.42000
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------


import System

/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
@System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")
@System.Diagnostics.DebuggerNonUserCodeAttribute
@System.Runtime.CompilerServices.CompilerGeneratedAttribute
internal class Resources {

    @System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")
    internal init() {
    }
    
    private static var resourceMan: System.Resources.ResourceManager¡
    
    private static var resourceCulture: System.Globalization.CultureInfo¡
    
    @System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)
    internal static var ResourceManager: System.Resources.ResourceManager¡ {
        get {
            if System.Object.ReferenceEquals(resourceMan, nil) {
                var temp: System.Resources.ResourceManager¡ = System.Resources.ResourceManager("TBLib.Properties.Resources", dynamicType(Resources).Assembly)
                resourceMan = temp
            }
            return resourceMan
        }
    }
    
    
    @System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)
    internal static var Culture: System.Globalization.CultureInfo¡ {
        get {
            return resourceCulture
        }
        set(value) { 
            resourceCulture = value
        }
    }
    
    
}

