//------------------------------------------------------------------------------
// <autogenerated>
//     This Oxygene source code was generated by a tool.
//     Runtime Version: 4.0.30319.42000
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------


@System.Runtime.CompilerServices.CompilerGeneratedAttribute
@System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")
internal final class Settings : System.Configuration.ApplicationSettingsBase {

    private static var defaultInstance: Settings¡ = (System.Configuration.ApplicationSettingsBase.Synchronized(Settings()) as! Settings)
    
    public static var Default: Settings¡ {
        get {
            return defaultInstance
        }
    }
    
    
}

