name: Crashes or Data Loss
description: Create a report if Toybox is crashing or lossing data
title: "<title>"
labels: ["bug", "crashes"]
body:
- type: textarea
  id: bugdescription
  attributes:
    label: Description of the bug
    description: Please give a clear and consise description of the bug you are experiencing
  validations:
    required: true
- type: textarea
  id: reproductionsteps
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. Go to...
      2. Click on...
      3. Scroll down to...
      4. See error...
  validations:
    required: true
- type: textarea
  id: expectedbehavior
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  id: logfiles
  attributes:
    label: Log Files
    description: Find your log files from the FAQ in the wiki
    placeholder: Drag and drop your log files here!
  validations:
    required: false
- type: textarea
  id: savefile
  attributes:
    label: Save File
    description: Zip your named save file (not an auto save!)
    placeholder: Drag and drop your zipped save file here!
  validations:
    required: false
- type: textarea
  id: screenshots
  attributes:
    label: Screenshots
    description: Screenshot of the bug
    placeholder: Drag and drop screenshots of the bug here!
  validations:
    required: false
- type: textarea
  id: settings
  attributes:
    label: Settings
    description: Please provide your settings file
    placeholder: Drag and drop your settings.xml file here!
  validations:
    required: false
- type: input
  id: toyboxversion
  attributes:
    label: Toybox Version
    description: Please provide the version of Toybox you are using
    placeholder: Example - 1.5.4c
  validations:
    required: true
- type: input
  id: os
  attributes:
    label: Operating System
    description: Please provide what operating system you use
    placeholder: Examples - Windows, MacOS
  validations:
    required: false
- type: dropdown
  id: whatgame
  attributes:
    label: What game are you using Toybox on?
    options:
      - Pathfinder Wrath of the Righteous
      - Rogue Trader
  validations:
    required: true
- type: input
  id: gameversion
  attributes:
    label: Game Version
    description: Please provide what version of the game you are on
    placeholder: Example - 2.1.4w
  validations:
    required: false
- type: textarea
  id: extrainfo
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
