name: Enhancement Request
description: Suggest an idea for this project
title: ''
labels: enhancement
body:
- type: textarea
  id: relatedtobug
  attributes:
    label: Is your feature request related to a problem?
    description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    render: markdown
  validations:
    required: true
- type: textarea
  id: proposedsolution
  attributes:
    label: Describe the solution you'd like
    description: A clear and concise description of what you want to happen
    render: markdown
  validations:
    required: true
- type: textarea
  id: altsolutions
  attributes:
    label: Describe alternatives you've considered
    description: A clear and concise description of any alternative solutions or features you've considered
    render: markdown
  validations:
    required: false
- type: textarea
  id: extrainfo
  attributes:
    label: Additional context
    description: Add any other context or screenshots about the feature request here
    render: markdown
  validations:
    required: false
